<?php

namespace Octava\Bundle\AdminMenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdminMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminMenuRepository extends EntityRepository
{
    public function getMenuTree()
    {
        $entities = $this->findBy([], ['position' => 'ASC']);
        $tree = $this->createTree($entities);
        return $tree;
    }

    /**
     * @param AdminMenu[] $entities
     * @param int|null $parentId
     * @param array $ret
     * @param int $level
     * @return array
     */
    protected function createTree(array $entities, $parentId = null, $ret = [], $level = 0)
    {
        foreach ($entities as $entity) {
            $parent = $entity->getParent();

            $needAppend = $parent instanceof AdminMenu && $parent->getId() == $parentId ||
                is_null($parent) && is_null($parentId);

            if ($needAppend) {
                $entity->setLevel($level);
                $ret[] = $entity;
                $ret = $this->createTree($entities, $entity->getId(), $ret, $level + 1);
            }
        }
        return $ret;
    }
}
