Octava\Bundle\AdminMenuBundle\Entity\AdminMenu:
    type: entity
    table: admin_menu
    repositoryClass: Octava\Bundle\AdminMenuBundle\Entity\AdminMenuRepository
    gedmo:
        translation:
            locale: locale

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        title:
            type: string
            length: 255
            gedmo:
                - translatable
        type:
            type: string
            length: 255
            options:
                comment: "folder|module"
        serviceId:
            type: string
            length: 255
            nullable: true
        position:
            type: integer
            gedmo:
                - sortablePosition

    lifecycleCallbacks:
        prePersist:   [ prePersist ]
        preUpdate:    [ preUpdate ]

    oneToMany:
        children:
            targetEntity: AdminMenu
            mappedBy: parent
            cascade: ['remove']
            orderBy:
                position: ASC

    manyToOne:
        parent:
            targetEntity: AdminMenu
            inversedBy: children
            joinColumn:
                onDelete: CASCADE
            gedmo:
                - sortableGroup
            cascade: ["persist", "merge"]
