parameters:
    octava_menu.cache.class: Doctrine\Common\Cache\FilesystemCache

services:
    octava_menu.cache:
        class: %octava_menu.cache.class%
        arguments: [%kernel.cache_dir%/structure]
