parameters:
    octava_menu.cache.class: Doctrine\Common\Cache\FilesystemCache
    octava_menu.admin.menu.class: Octava\Bundle\MenuBundle\Admin\MenuAdmin
    octava_menu.config.menu_config.class: Octava\Bundle\MenuBundle\Config\MenuConfig
    octava_menu.menu_manager.class: Octava\Bundle\MenuBundle\MenuManager
    octava_menu.event_listener.structure_item_update.class: Octava\Bundle\MenuBundle\EventListener\StructureItemUpdate
    octava_menu.form_type.menu_related_text_type.class: Octava\Bundle\MenuBundle\Form\Type\MenuRelatedTextType
    octava_menu.helper.import_from_structure.class: Octava\Bundle\MenuBundle\Helper\ImportFromStructure
    octava_menu.twig.menu_extension.class: Octava\Bundle\MenuBundle\Twig\MenuExtension
    octava_menu.twig.breadcrumbs_extension.class: Octava\Bundle\MenuBundle\Twig\BreadcrumbsExtension
    octava_menu.filter_chain.class: Octava\Bundle\MenuBundle\Filter\FilterChain

services:
    octava_menu.cache:
        class: %octava_menu.cache.class%
        arguments: [%kernel.cache_dir%/structure]

    octava_menu.admin.menu:
        class: %octava_menu.admin.menu.class%
        arguments: [~, Octava\Bundle\MenuBundle\Entity\Menu, OctavaMenuBundle:MenuAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: Menu }
    octava_menu.menu_manager:
        class: %octava_menu.menu_manager.class%
        arguments:
         - '@octava_mui.translation_manager'
         - '@octava_menu.config.menu_config'
         - '@octava_menu.cache'

    octava_menu.event_listener.structure_item_update:
        class: %octava_menu.event_listener.structure_item_update.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@octava_menu.cache'
            - %kernel.default_locale%
        tags:
            - { name: kernel.event_subscriber }

    octava_menu.form_type.menu_related_text_type:
        class: %octava_menu.form_type.menu_related_text_type.class%
        tags:
            - { name: form.type, alias: octava_menu_related_text }

    octava_menu.helper.import_from_structure:
        class: %octava_menu.helper.import_from_structure.class%
        arguments: [ '@doctrine.orm.entity_manager', '@octava_mui.locale_manager' ]

    octava_menu.filter_chain:
        class: %octava_menu.filter_chain.class%

    octava_menu.twig.menu_extension:
        class: %octava_menu.twig.menu_extension.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@octava_structure.structure_manager'
            - '@octava_menu.cache'
            - '@octava_menu.filter_chain'
            - '@request_stack'
        tags:
            - { name: twig.extension }

    octava_menu.twig.breadcrumbs_extension:
        class: %octava_menu.twig.breadcrumbs_extension.class%
        arguments: [ '@octava_structure.structure_manager', '@octava_mui.office_manager' ]
        tags:
            - { name: twig.extension }
