parameters:
    octava_admin.translator.label_translator_strategy.class: Octava\Bundle\AdminBundle\Translator\LabelTranslatorStrategy

services:
    octava_admin.translator.label_translator_strategy:
        class: %octava_admin.translator.label_translator_strategy.class%
        calls:
            - [ setTranslator, [@translator] ]
