parameters:
    octava_administrator.security_handler.administrator.class: Octava\Bundle\AdministratorBundle\Security\Handler\AdministratorHandler
    octava_administrator.admin.administrator.class: Octava\Bundle\AdministratorBundle\Admin\AdministratorAdmin
    octava_administrator.admin.group: Octava\Bundle\AdministratorBundle\Admin\GroupAdmin
    octava_administrator.config.administrator.class: Octava\Bundle\AdministratorBundle\Config\AdministratorConfig
    octava_administrator.form_type.resources.class: Octava\Bundle\AdministratorBundle\Form\Type\ResourcesType
    octava_administrator.twig.administrator_extension.class: Octava\Bundle\AdministratorBundle\Twig\AdministratorExtension

services:
    octava_administrator.security_handler.administrator:
        class: %octava_administrator.security_handler.administrator.class%
        arguments: [ @doctrine.orm.entity_manager, @security.token_storage ]

    octava_administrator.form_type.resources:
        class: %octava_administrator.form_type.resources.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @translator.logging
            - @security.token_storage
            - @octava_administrator.config.administrator
        tags:
            - { name: form.type, alias: octava_acl_resources }

    octava_administrator.twig.administrator_extension:
        class: %octava_administrator.twig.administrator_extension.class%
        arguments: [ @security.token_storage ]
        tags:
            - { name: twig.extension }
