parameters:
    octava_admin_menu.admin_menu_manager.class: Octava\Bundle\AdminMenuBundle\AdminMenuManager
    octava_admin_menu.dict.types.class: Octava\Bundle\AdminMenuBundle\Dict\Types
    octava_admin_menu.admin.admin_menu.class: Octava\Bundle\AdminMenuBundle\Admin\AdminMenuAdmin
    octava_admin_menu.twig.admin_menu_extension.class: Octava\Bundle\AdminMenuBundle\Twig\AdminMenuExtension
    octava_admin_menu.form_type.entity_type.class: Octava\Bundle\AdminMenuBundle\Form\Type\EntityType
    octava_admin_menu.form_type.admin_class_choice_type.class: Octava\Bundle\AdminMenuBundle\Form\Type\AdminClassChoiceType
    octava_admin_menu.builder.class: Octava\Bundle\AdminMenuBundle\Builder

services:
    octava_admin_menu.admin_menu_manager:
        class: %octava_admin_menu.admin_menu_manager.class%
        arguments: [ @sonata.admin.pool, @translator, @doctrine.orm.entity_manager ]

    octava_admin_menu.dict.types:
        class: %octava_admin_menu.dict.types.class%
        arguments: [ @translator ]

    octava_admin_menu.admin.admin_menu:
        class: %octava_admin_menu.admin.admin_menu.class%
        arguments: [~, Octava\Bundle\AdminMenuBundle\Entity\AdminMenu, OctavaAdminMenuBundle:AdminMenuAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Admin, label: "Admin Menu"}

    octava_admin_menu.twig.admin_menu_extension:
        class: %octava_admin_menu.twig.admin_menu_extension.class%
        public: false
        arguments: [@octava_admin_menu.admin_menu_manager]
        tags:
            - { name: twig.extension }

    octava_admin_menu.form_type.entity_type:
        class: %octava_admin_menu.form_type.entity_type.class%
        arguments: [ @octava_admin_menu.admin_menu_manager ]
        tags:
            - { name: form.type, alias: octava_admin_menu_entity }

    octava_admin_menu.form_type.admin_class_choice_type:
        class: %octava_admin_menu.form_type.admin_class_choice_type.class%
        arguments: [ @octava_admin_menu.admin_menu_manager ]
        tags:
            - { name: form.type, alias: octava_admin_menu_admin_class_choice }

    octava_admin_menu.builder:
        class: %octava_admin_menu.builder.class%
        arguments:
            - @sonata.admin.pool
            - @knp_menu.factory
            - @knp_menu.menu_provider
            - @event_dispatcher
            - @request_stack
            - @octava_admin_menu.admin_menu_manager
