imports:
    - { resource: services/locale.yml }
    - { resource: services/office.yml }

services:
    octava_mui.router.default_pattern_generation_strategy:
        class: Octava\Bundle\MuiBundle\Router\DefaultPatternGenerationStrategy
        arguments:
            - %jms_i18n_routing.strategy%
            - @translator
            - %jms_i18n_routing.locales%
            - %kernel.cache_dir%
            - %jms_i18n_routing.catalogue%
            - %jms_i18n_routing.default_locale%
        calls:
            - [ setContainer, [@service_container] ]


    octava_mui.admin.translation:
        class: Octava\Bundle\MuiBundle\Admin\TranslationAdmin
        arguments: [~, Octava\Bundle\MuiBundle\Entity\Translation, OctavaMuiBundle:TranslationAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Translation}
